# Generated by Django 4.0.6 on 2022-07-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='For teachers', verbose_name='teacher status'),
        ),
    ]
